language: node_js
node_js:
  - "0.10"

before_deploy: "cd build/src"

deploy:
  provider: npm
  email: hendrik@helwich.de
  api_key:
    secure: PUUs2ajF50L6HQk1n6UqGkCdooDyxrc3XdjdJ9+REnymGhJQ0/1f9xdjUVh1HDZ2lGh5WbGLiinUsB4YWYIqbT3AXpi+CpKYHB0xHxnaqs5EcL7WorarNSIY8gaZxvhBCbqkYTZFkzzhwBEg4mpQKfi9AMERPtWSujhWVN5vPuU=
  on:
    tags: true
  skip_cleanup: true
env:
  global:
  - secure: yFiSsYp1lhq7ISOMP/ySpUm5tJdMSn+uqBhGIbg0+7rwCBHutAvVWrHkbp0G6QF6XyUZzFC2+iI/zTzmhl6FIpQEyw6Qvv30CcaYE3+6DG6Pw/NTkj7kCjwguuabKLePNknhYDYD0sN4S7EIvoY+zVMXcdanjXx0pWCtL1seCos=
  - secure: OEEQGxpKYqBJ1Sw7glV7HrYIYm6hp5/vsYAtPTMcEt1+Xu84qS9uxgyDA77XTe3IvdzoSrsKJT3nx9EmeKr6q7ChNuI+QwGx5oE29l97jGg/g2wkbcKHurwaxw204OrUO6yRyDC/AhsJDz5C7t1oUB86srwDokAeIIxKhJ6a+Tk=
